apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    run: my-app
    type: frontend
spec:
  template:
    metadata:
      name: my-pod
      labels:
        run: app
        type: frontend
    spec:
      containers:
      - name: my-app
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend
